const SUPABASE_URL="https://jqcqdpgzirrhitqqzdgn.supabase.co";
const SUPABASE_KEY="sb_publishable_EdBUU4jPfp7jwfandF_5GQ_kdBnGmWm";
const $=selector=>document.querySelector(selector);
let session=JSON.parse(localStorage.getItem("microlocsAdminSession")||"null");
let weekStart=mondayFor(new Date());
const money=value=>new Intl.NumberFormat("en-KE",{style:"currency",currency:"KES",maximumFractionDigits:0}).format(Number(value)||0);
const isoDate=date=>new Intl.DateTimeFormat("en-CA",{timeZone:"Africa/Nairobi",year:"numeric",month:"2-digit",day:"2-digit"}).format(date);
const escapeHtml=value=>String(value||"").replace(/[&<>"']/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[char]));
function mondayFor(value){const date=new Date(value),name=new Intl.DateTimeFormat("en-US",{timeZone:"Africa/Nairobi",weekday:"short"}).format(date),day=name==="Sun"?7:["Mon","Tue","Wed","Thu","Fri","Sat"].indexOf(name)+1;date.setDate(date.getDate()-day+1);date.setHours(12,0,0,0);return date}
const weekEnd=()=>{const date=new Date(weekStart);date.setDate(date.getDate()+5);return date};
const authHeaders=(extra={})=>({apikey:SUPABASE_KEY,Authorization:`Bearer ${session?.access_token||""}`,...extra});
async function api(path,options={}){const response=await fetch(`${SUPABASE_URL}${path}`,{...options,headers:authHeaders(options.headers)}),data=await response.json().catch(()=>null);if(!response.ok)throw new Error(data?.msg||data?.message||data?.error_description||"Request failed");return data}
async function confirmAdmin(){const rows=await api(`/rest/v1/admin_users?user_id=eq.${encodeURIComponent(session.user.id)}&select=user_id,email`);if(!rows.length)throw new Error("This account is not authorised as an admin");return rows[0]}
function showLogin(message=""){session=null;localStorage.removeItem("microlocsAdminSession");$("#loginView").hidden=false;$("#dashboard").hidden=true;$("#signOut").hidden=true;$("#loginMessage").textContent=message}
async function showDashboard(){try{const admin=await confirmAdmin();$("#loginView").hidden=true;$("#dashboard").hidden=false;$("#signOut").hidden=false;$("#adminEmail").textContent=admin.email;await refreshWeek()}catch(error){showLogin(error.message)}}
$("#loginForm").onsubmit=async event=>{event.preventDefault();const button=event.currentTarget.querySelector('button[type="submit"]'),values=Object.fromEntries(new FormData(event.currentTarget));button.disabled=true;$("#loginMessage").textContent="Signing in…";try{session=await api("/auth/v1/token?grant_type=password",{method:"POST",headers:{"Content-Type":"application/json",apikey:SUPABASE_KEY,Authorization:""},body:JSON.stringify(values)});localStorage.setItem("microlocsAdminSession",JSON.stringify(session));await showDashboard()}catch(error){showLogin(error.message)}finally{button.disabled=false}};
$("#signOut").onclick=()=>showLogin("You have signed out.");
function renderWeekLabel(){const options={day:"numeric",month:"short",year:"numeric",timeZone:"Africa/Nairobi"};$("#weekLabel").textContent=`${weekStart.toLocaleDateString("en-KE",options)} – ${weekEnd().toLocaleDateString("en-KE",options)}`}
async function getJobs(){return api(`/rest/v1/commission_jobs?week_start=eq.${isoDate(weekStart)}&select=*&order=completed_at.asc`)}
function renderCalendar(events){
 const days=["Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"];
 $("#weeklyCalendar").innerHTML=`<div class="calendar-grid">${days.map(day=>{const rows=events.filter(event=>new Date(event.starts_at).toLocaleDateString("en-US",{weekday:"long",timeZone:"Africa/Nairobi"})===day);return `<section><h3>${day}</h3>${rows.length?rows.map(event=>`<article class="${event.completed?"done":""}"><time>${new Date(event.starts_at).toLocaleTimeString("en-KE",{hour:"numeric",minute:"2-digit",timeZone:"Africa/Nairobi"})}</time><strong>${escapeHtml(event.customer_name)}</strong><small>${escapeHtml(event.service)} · ${escapeHtml(event.worker)}</small><span>${event.completed?"Completed":"Booked"}</span></article>`).join(""):'<p class="no-booking">No bookings</p>'}</section>`}).join("")}</div>`;
 const ordered=days.flatMap(day=>events.filter(event=>new Date(event.starts_at).toLocaleDateString("en-US",{weekday:"long",timeZone:"Africa/Nairobi"})===day));
 document.querySelectorAll("#weeklyCalendar article").forEach((article,index)=>{const booking=ordered[index];if(!booking)return;const button=document.createElement("button");button.type="button";button.className="delete-booking";button.textContent="Delete booking";button.onclick=()=>removeBooking(booking.calendar_event_id,button);article.appendChild(button)});
}
async function removeBooking(eventId,button){if(!confirm("Delete this booking from Google Calendar?"))return;button.disabled=true;button.textContent="Deleting…";try{const response=await fetch(`/api/delete-booking?id=${encodeURIComponent(eventId)}`,{method:"DELETE",headers:{Authorization:`Bearer ${session.access_token}`}}),data=await response.json();if(!response.ok)throw new Error(data.error||"Could not delete booking");await api(`/rest/v1/commission_jobs?calendar_event_id=eq.${encodeURIComponent(eventId)}`,{method:"DELETE",headers:{Prefer:"return=minimal"}});await refreshWeek()}catch(error){button.disabled=false;button.textContent="Delete booking";$("#syncMessage").textContent=error.message}}
function renderJobs(jobs){
 const breeTotal=jobs.filter(job=>job.worker==="Bree").reduce((sum,job)=>sum+Number(job.commission_amount||0),0),joanTotal=jobs.filter(job=>job.worker==="Joan").reduce((sum,job)=>sum+Number(job.commission_amount||0),0),weekSaved=jobs.length&&jobs.every(job=>job.week_saved_at);
 $("#summaryGrid").innerHTML=["Bree","Joan"].map(worker=>{const rows=jobs.filter(job=>job.worker===worker),final=rows.reduce((sum,job)=>sum+Number(job.final_amount||0),0),commission=rows.reduce((sum,job)=>sum+Number(job.commission_amount||0),0),unpaid=rows.filter(job=>!job.is_paid).reduce((sum,job)=>sum+Number(job.commission_amount||0),0);return `<article><span>${worker}</span><strong>${money(commission)}</strong><small>40% commission · ${rows.length} job${rows.length===1?"":"s"}</small><div><b>${money(final)}</b> collected · <b>${money(unpaid)}</b> unpaid</div></article>`}).join("");
 $("#jobCount").textContent=`${jobs.length} job${jobs.length===1?"":"s"}`;
 $("#jobsTable").innerHTML=jobs.length?`<div class="table detailed"><div class="table-head"><span>Customer details</span><span>Worker</span><span>Final amount</span><span>40% commission</span><span>Status</span></div>${jobs.map(job=>`<div class="table-row"><span class="customer-details"><input data-name="${job.id}" value="${escapeHtml(job.customer_name)}" aria-label="Customer name"><small>${escapeHtml(job.service)} · ${new Date(job.completed_at).toLocaleString("en-KE",{weekday:"short",day:"numeric",month:"short",hour:"numeric",minute:"2-digit",timeZone:"Africa/Nairobi"})}</small>${job.customer_phone?`<a href="tel:${escapeHtml(job.customer_phone)}">${escapeHtml(job.customer_phone)}</a>`:""}${job.customer_email?`<a href="mailto:${escapeHtml(job.customer_email)}">${escapeHtml(job.customer_email)}</a>`:""}${job.booking_notes?`<small>${escapeHtml(job.booking_notes)}</small>`:""}</span><span><select data-worker="${job.id}" aria-label="Worker"><option ${job.worker==="Unassigned"?"selected":""}>Unassigned</option><option ${job.worker==="Bree"?"selected":""}>Bree</option><option ${job.worker==="Joan"?"selected":""}>Joan</option></select></span><span><label class="amount"><small>KSh</small><input data-amount="${job.id}" type="number" min="0" step="1" value="${job.final_amount??""}" placeholder="0"></label></span><span>${money(job.commission_amount)}</span><span><label class="paid"><input data-paid="${job.id}" type="checkbox" ${job.is_paid?"checked":""}><i></i>${job.is_paid?"Paid":"Unpaid"}</label></span></div>`).join("")}</div>`:'<div class="empty"><strong>No completed jobs yet for this week.</strong><span>Bookings appear here automatically after their calendar end time.</span></div>';
 if(jobs.length)$("#jobsTable").insertAdjacentHTML("beforeend",`<div class="bottom-commission"><article><span>Bree receives</span><strong>${money(breeTotal)}</strong></article><article><span>Joan receives</span><strong>${money(joanTotal)}</strong></article><button id="saveWeek">Save this week’s work</button><p id="saveWeekMessage">${weekSaved?"This week’s work has been saved.":""}</p></div>`);
 document.querySelectorAll("[data-name]").forEach(input=>input.onchange=()=>updateJob(input.dataset.name,{customer_name:input.value.trim()||"Customer"}));
 document.querySelectorAll("[data-worker]").forEach(select=>select.onchange=()=>updateJob(select.dataset.worker,{worker:select.value}));
 document.querySelectorAll("[data-amount]").forEach(input=>input.onchange=()=>updateJob(input.dataset.amount,{final_amount:input.value===""?null:Number(input.value)}));
 document.querySelectorAll("[data-paid]").forEach(input=>input.onchange=()=>updateJob(input.dataset.paid,{is_paid:input.checked}));
 if($("#saveWeek"))$("#saveWeek").onclick=saveWeek;
}
async function saveWeek(){const button=$("#saveWeek");button.disabled=true;$("#saveWeekMessage").textContent="Saving this week…";try{await api(`/rest/v1/commission_jobs?week_start=eq.${isoDate(weekStart)}`,{method:"PATCH",headers:{"Content-Type":"application/json","Prefer":"return=minimal"},body:JSON.stringify({week_saved_at:new Date().toISOString()})});$("#saveWeekMessage").textContent="This week’s work has been saved.";await loadHistory()}catch(error){$("#saveWeekMessage").textContent=error.message}finally{button.disabled=false}}
async function updateJob(id,changes){try{await api(`/rest/v1/commission_jobs?id=eq.${id}`,{method:"PATCH",headers:{"Content-Type":"application/json","Prefer":"return=minimal"},body:JSON.stringify(changes)});await loadSavedWeek()}catch(error){$("#syncMessage").textContent=error.message}}
async function loadHistory(){const rows=await api("/rest/v1/commission_jobs?select=week_start,commission_amount,is_paid&order=week_start.desc"),weeks=[...new Set(rows.map(row=>row.week_start))].slice(0,12);$("#historyList").innerHTML=weeks.map(week=>{const items=rows.filter(row=>row.week_start===week),total=items.reduce((sum,row)=>sum+Number(row.commission_amount||0),0),paid=items.length&&items.every(row=>row.is_paid);return `<button data-week="${week}"><span>Week of ${new Date(`${week}T12:00:00+03:00`).toLocaleDateString("en-KE",{day:"numeric",month:"short",year:"numeric"})}</span><strong>${money(total)} · ${paid?"Paid":"Payment pending"}</strong></button>`}).join("")||"<p>No earlier records yet.</p>";document.querySelectorAll("[data-week]").forEach(button=>button.onclick=()=>{weekStart=new Date(`${button.dataset.week}T12:00:00+03:00`);refreshWeek()})}
async function loadSavedWeek(){renderWeekLabel();renderJobs(await getJobs());await loadHistory()}
const walkinDate=$("#walkinForm [name=completed_at]");
const setWalkinNow=()=>{walkinDate.value=new Intl.DateTimeFormat("sv-SE",{timeZone:"Africa/Nairobi",year:"numeric",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit"}).format(new Date()).replace(" ","T")};
setWalkinNow();
$("#walkinForm").onsubmit=async event=>{event.preventDefault();const form=event.currentTarget,button=form.querySelector('button[type="submit"]'),values=Object.fromEntries(new FormData(form)),completed=new Date(`${values.completed_at}:00+03:00`),start=mondayFor(completed),end=new Date(start);end.setDate(end.getDate()+5);button.disabled=true;$("#walkinMessage").textContent="Saving walk-in…";try{await api("/rest/v1/commission_jobs",{method:"POST",headers:{"Content-Type":"application/json","Prefer":"return=minimal"},body:JSON.stringify({calendar_event_id:`manual-${crypto.randomUUID()}`,worker:values.worker,customer_name:values.customer_name.trim(),customer_phone:values.customer_phone.trim(),service:values.service.trim(),booking_notes:values.booking_notes.trim(),completed_at:completed.toISOString(),week_start:isoDate(start),week_end:isoDate(end),final_amount:Number(values.final_amount)})});weekStart=start;form.reset();setWalkinNow();$("#walkinMessage").textContent="Walk-in saved. The 40% commission has been calculated.";await loadSavedWeek()}catch(error){$("#walkinMessage").textContent=error.message}finally{button.disabled=false}};
async function refreshWeek(){const button=$("#importCalendar");button.disabled=true;$("#syncMessage").textContent="Loading this week’s calendar…";try{const start=isoDate(weekStart),end=isoDate(weekEnd()),response=await fetch(`/api/admin-calendar?start=${start}&end=${end}`,{headers:{Authorization:`Bearer ${session.access_token}`}}),data=await response.json();if(!response.ok)throw new Error(data.error||"Calendar unavailable");renderCalendar(data.calendar||[]);if(data.jobs.length)await api("/rest/v1/commission_jobs?on_conflict=calendar_event_id",{method:"POST",headers:{"Content-Type":"application/json","Prefer":"resolution=ignore-duplicates,return=minimal"},body:JSON.stringify(data.jobs)});$("#syncMessage").textContent=`${data.calendar.length} booking${data.calendar.length===1?"":"s"} found · ${data.jobs.length} completed.`;await loadSavedWeek()}catch(error){$("#syncMessage").textContent=error.message;await loadSavedWeek()}finally{button.disabled=false}}
$("#importCalendar").onclick=refreshWeek;
$("#previousWeek").onclick=()=>{weekStart.setDate(weekStart.getDate()-7);refreshWeek()};
$("#nextWeek").onclick=()=>{weekStart.setDate(weekStart.getDate()+7);refreshWeek()};
session?.access_token?showDashboard():showLogin();
