const SUPABASE_URL="https://jqcqdpgzirrhitqqzdgn.supabase.co",SUPABASE_KEY="sb_publishable_EdBUU4jPfp7jwfandF_5GQ_kdBnGmWm",$=s=>document.querySelector(s);
let session=JSON.parse(localStorage.getItem("microlocsAdminSession")||"null"),weekStart=mondayFor(new Date());
const money=v=>new Intl.NumberFormat("en-KE",{style:"currency",currency:"KES",maximumFractionDigits:0}).format(Number(v)||0),isoDate=d=>new Intl.DateTimeFormat("en-CA",{timeZone:"Africa/Nairobi",year:"numeric",month:"2-digit",day:"2-digit"}).format(d);
function mondayFor(value){const d=new Date(value),name=new Intl.DateTimeFormat("en-US",{timeZone:"Africa/Nairobi",weekday:"short"}).format(d),day=name==="Sun"?7:["Mon","Tue","Wed","Thu","Fri","Sat"].indexOf(name)+1;d.setDate(d.getDate()-day+1);d.setHours(12,0,0,0);return d}const weekEnd=()=>{const d=new Date(weekStart);d.setDate(d.getDate()+5);return d};
const authHeaders=(extra={})=>({apikey:SUPABASE_KEY,Authorization:`Bearer ${session?.access_token||""}`,...extra});
async function api(path,options={}){const response=await fetch(`${SUPABASE_URL}${path}`,{...options,headers:authHeaders(options.headers)}),data=await response.json().catch(()=>null);if(!response.ok)throw new Error(data?.msg||data?.message||data?.error_description||"Request failed");return data}
async function confirmAdmin(){const rows=await api(`/rest/v1/admin_users?user_id=eq.${encodeURIComponent(session.user.id)}&select=user_id,email`);if(!rows.length)throw new Error("This account is not authorised as an admin");return rows[0]}
function showLogin(message=""){session=null;localStorage.removeItem("microlocsAdminSession");$("#loginView").hidden=false;$("#dashboard").hidden=true;$("#signOut").hidden=true;$("#loginMessage").textContent=message}
async function showDashboard(){try{const admin=await confirmAdmin();$("#loginView").hidden=true;$("#dashboard").hidden=false;$("#signOut").hidden=false;$("#adminEmail").textContent=admin.email;await loadWeek()}catch(error){showLogin(error.message)}}
$("#loginForm").onsubmit=async e=>{e.preventDefault();const button=e.currentTarget.querySelector('button[type="submit"]'),values=Object.fromEntries(new FormData(e.currentTarget));button.disabled=true;$("#loginMessage").textContent="Signing in…";try{session=await api("/auth/v1/token?grant_type=password",{method:"POST",headers:{"Content-Type":"application/json",apikey:SUPABASE_KEY,Authorization:""},body:JSON.stringify(values)});localStorage.setItem("microlocsAdminSession",JSON.stringify(session));await showDashboard()}catch(error){showLogin(error.message)}finally{button.disabled=false}};
$("#signOut").onclick=()=>showLogin("You have signed out.");
function renderWeekLabel(){const options={day:"numeric",month:"short",year:"numeric",timeZone:"Africa/Nairobi"};$("#weekLabel").textContent=`${weekStart.toLocaleDateString("en-KE",options)} – ${weekEnd().toLocaleDateString("en-KE",options)}`}
async function getJobs(){return api(`/rest/v1/commission_jobs?week_start=eq.${isoDate(weekStart)}&select=*&order=completed_at.asc`)}
const escapeHtml=v=>String(v||"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
function renderJobs(jobs){
 $("#summaryGrid").innerHTML=["Bree","Joan"].map(worker=>{const rows=jobs.filter(j=>j.worker===worker),final=rows.reduce((s,j)=>s+Number(j.final_amount||0),0),commission=rows.reduce((s,j)=>s+Number(j.commission_amount||0),0),unpaid=rows.filter(j=>!j.is_paid).reduce((s,j)=>s+Number(j.commission_amount||0),0);return `<article><span>${worker}</span><strong>${money(commission)}</strong><small>40% commission · ${rows.length} job${rows.length===1?"":"s"}</small><div><b>${money(final)}</b> collected · <b>${money(unpaid)}</b> unpaid</div></article>`}).join("");$("#jobCount").textContent=`${jobs.length} job${jobs.length===1?"":"s"}`;
 $("#jobsTable").innerHTML=jobs.length?`<div class="table"><div class="table-head"><span>Job</span><span>Worker</span><span>Final amount</span><span>40% commission</span><span>Status</span></div>${jobs.map(j=>`<div class="table-row"><span><strong>${escapeHtml(j.customer_name)}</strong><small>${escapeHtml(j.service)} · ${new Date(j.completed_at).toLocaleString("en-KE",{weekday:"short",hour:"numeric",minute:"2-digit",timeZone:"Africa/Nairobi"})}</small></span><span><b class="worker">${j.worker}</b></span><span><label class="amount"><small>KSh</small><input data-amount="${j.id}" type="number" min="0" step="1" value="${j.final_amount??""}" placeholder="0"></label></span><span>${money(j.commission_amount)}</span><span><label class="paid"><input data-paid="${j.id}" type="checkbox" ${j.is_paid?"checked":""}><i></i>${j.is_paid?"Paid":"Unpaid"}</label></span></div>`).join("")}</div>`:'<div class="empty"><strong>No completed jobs imported for this week.</strong><span>Use “Import completed calendar jobs” to check Bree and Joan’s appointments.</span></div>';
 document.querySelectorAll("[data-amount]").forEach(input=>input.onchange=()=>updateJob(input.dataset.amount,{final_amount:input.value===""?null:Number(input.value)}));document.querySelectorAll("[data-paid]").forEach(input=>input.onchange=()=>updateJob(input.dataset.paid,{is_paid:input.checked}));
}
async function updateJob(id,changes){try{await api(`/rest/v1/commission_jobs?id=eq.${id}`,{method:"PATCH",headers:{"Content-Type":"application/json","Prefer":"return=minimal"},body:JSON.stringify(changes)});await loadWeek()}catch(error){$("#syncMessage").textContent=error.message}}
async function loadHistory(){const rows=await api("/rest/v1/commission_jobs?select=week_start,commission_amount,is_paid&order=week_start.desc"),weeks=[...new Set(rows.map(r=>r.week_start))].slice(0,12);$("#historyList").innerHTML=weeks.map(week=>{const items=rows.filter(r=>r.week_start===week),total=items.reduce((s,r)=>s+Number(r.commission_amount||0),0),paid=items.length&&items.every(r=>r.is_paid);return `<button data-week="${week}"><span>Week of ${new Date(`${week}T12:00:00+03:00`).toLocaleDateString("en-KE",{day:"numeric",month:"short",year:"numeric"})}</span><strong>${money(total)} · ${paid?"Paid":"Payment pending"}</strong></button>`}).join("")||"<p>No earlier records yet.</p>";document.querySelectorAll("[data-week]").forEach(button=>button.onclick=()=>{weekStart=new Date(`${button.dataset.week}T12:00:00+03:00`);loadWeek()})}
async function loadWeek(){renderWeekLabel();renderJobs(await getJobs());await loadHistory()}
$("#importCalendar").onclick=async()=>{const button=$("#importCalendar");button.disabled=true;$("#syncMessage").textContent="Checking completed appointments…";try{const start=isoDate(weekStart),end=isoDate(weekEnd()),response=await fetch(`/api/admin-calendar?start=${start}&end=${end}`,{headers:{Authorization:`Bearer ${session.access_token}`}}),data=await response.json();if(!response.ok)throw new Error(data.error||"Calendar import failed");if(data.jobs.length)await api("/rest/v1/commission_jobs?on_conflict=calendar_event_id",{method:"POST",headers:{"Content-Type":"application/json","Prefer":"resolution=ignore-duplicates,return=minimal"},body:JSON.stringify(data.jobs)});$("#syncMessage").textContent=`Imported ${data.jobs.length} completed job${data.jobs.length===1?"":"s"}.`;await loadWeek()}catch(error){$("#syncMessage").textContent=error.message}finally{button.disabled=false}};
$("#previousWeek").onclick=()=>{weekStart.setDate(weekStart.getDate()-7);loadWeek()};$("#nextWeek").onclick=()=>{weekStart.setDate(weekStart.getDate()+7);loadWeek()};session?.access_token?showDashboard():showLogin();
