const SUPABASE_URL="https://jqcqdpgzirrhitqqzdgn.supabase.co";
const SUPABASE_KEY="sb_publishable_EdBUU4jPfp7jwfandF_5GQ_kdBnGmWm";
const $=selector=>document.querySelector(selector);
let session=JSON.parse(localStorage.getItem("microlocsAdminSession")||"null");
let weekStart=mondayFor(new Date());
const money=value=>new Intl.NumberFormat("en-KE",{style:"currency",currency:"KES",maximumFractionDigits:0}).format(Number(value)||0);
const isoDate=date=>new Intl.DateTimeFormat("en-CA",{timeZone:"Africa/Nairobi",year:"numeric",month:"2-digit",day:"2-digit"}).format(date);
const escapeHtml=value=>String(value||"").replace(/[&<>"']/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[char]));
function mondayFor(value){const date=new Date(value),name=new Intl.DateTimeFormat("en-US",{timeZone:"Africa/Nairobi",weekday:"short"}).format(date),day=name==="Sun"?7:["Mon","Tue","Wed","Thu","Fri","Sat"].indexOf(name)+1;date.setDate(date.getDate()-day+1);date.setHours(12,0,0,0);return date}
const weekEnd=()=>{const date=new Date(weekStart);date.setDate(date.getDate()+5);return date};
const authHeaders=(extra={})=>({apikey:SUPABASE_KEY,Authorization:`Bearer ${session?.access_token||""}`,...extra});
async function api(path,options={}){const response=await fetch(`${SUPABASE_URL}${path}`,{...options,headers:authHeaders(options.headers)}),data=await response.json().catch(()=>null);if(!response.ok)throw new Error(data?.msg||data?.message||data?.error_description||"Request failed");return data}
async function confirmAdmin(){const rows=await api(`/rest/v1/admin_users?user_id=eq.${encodeURIComponent(session.user.id)}&select=user_id,email`);if(!rows.length)throw new Error("This account is not authorised as an admin");return rows[0]}
function showLogin(message=""){session=null;customerListRequest++;customerDetailRequest++;$("#customerList").innerHTML="";$("#customerAccountDetail").innerHTML="";localStorage.removeItem("microlocsAdminSession");$("#loginView").hidden=false;$("#dashboard").hidden=true;$("#signOut").hidden=true;$("#loginMessage").textContent=message}
async function showDashboard(){try{const admin=await confirmAdmin();$("#loginView").hidden=true;$("#dashboard").hidden=false;$("#signOut").hidden=false;$("#adminEmail").textContent=admin.email;await refreshWeek();loadCustomers()}catch(error){showLogin(error.message)}}
$("#loginForm").onsubmit=async event=>{event.preventDefault();const button=event.currentTarget.querySelector('button[type="submit"]'),values=Object.fromEntries(new FormData(event.currentTarget));button.disabled=true;$("#loginMessage").textContent="Signing in…";try{session=await api("/auth/v1/token?grant_type=password",{method:"POST",headers:{"Content-Type":"application/json",apikey:SUPABASE_KEY,Authorization:""},body:JSON.stringify(values)});localStorage.setItem("microlocsAdminSession",JSON.stringify(session));await showDashboard()}catch(error){showLogin(error.message)}finally{button.disabled=false}};
$("#signOut").onclick=()=>showLogin("You have signed out.");
function renderWeekLabel(){const options={day:"numeric",month:"short",year:"numeric",timeZone:"Africa/Nairobi"};$("#weekLabel").textContent=`${weekStart.toLocaleDateString("en-KE",options)} – ${weekEnd().toLocaleDateString("en-KE",options)}`}
async function getJobs(){return api(`/rest/v1/commission_jobs?week_start=eq.${isoDate(weekStart)}&select=*&order=completed_at.asc`)}
function renderBookingDetails(event){
 const options=(event.booking_options||[]).map(option=>`<div><dt>${escapeHtml(option.label)}</dt><dd>${escapeHtml(option.value)}</dd></div>`).join("");
 return `<div class="appointment-details"><p class="booking-drink"><b>Drink:</b> ${escapeHtml(event.beverage||"Not recorded")}</p><details><summary>View booking details</summary><dl>${event.customer_phone?`<div><dt>Phone</dt><dd>${escapeHtml(event.customer_phone)}</dd></div>`:""}${event.customer_email?`<div><dt>Email</dt><dd>${escapeHtml(event.customer_email)}</dd></div>`:""}${options}</dl>${event.hair_details?`<p class="hair-notes"><b>Hair details:</b> ${escapeHtml(event.hair_details)}</p>`:""}${!(event.booking_options||[]).some(option=>option.label!=="Duration")?'<p class="missing-options">No selected options recorded.</p>':""}</details></div>`;
}
function renderCalendar(events){
 const days=["Monday","Tuesday","Wednesday","Thursday","Friday","Saturday"];
 $("#weeklyCalendar").innerHTML=`<div class="calendar-grid">${days.map(day=>{const rows=events.filter(event=>new Date(event.starts_at).toLocaleDateString("en-US",{weekday:"long",timeZone:"Africa/Nairobi"})===day);return `<section><h3>${day}</h3>${rows.length?rows.map(event=>`<article class="${event.completed?"done":""}"><time>${new Date(event.starts_at).toLocaleTimeString("en-KE",{hour:"numeric",minute:"2-digit",timeZone:"Africa/Nairobi"})}</time><strong>${escapeHtml(event.customer_name)}</strong><small>${escapeHtml(event.service)} · ${escapeHtml(event.stylist||event.worker)}</small><span>${event.completed?"Completed":"Booked"}</span>${renderBookingDetails(event)}</article>`).join(""):'<p class="no-booking">No bookings</p>'}</section>`}).join("")}</div>`;
 const ordered=days.flatMap(day=>events.filter(event=>new Date(event.starts_at).toLocaleDateString("en-US",{weekday:"long",timeZone:"Africa/Nairobi"})===day));
 document.querySelectorAll("#weeklyCalendar article").forEach((article,index)=>{const booking=ordered[index];if(!booking)return;const button=document.createElement("button");button.type="button";button.className="delete-booking";button.textContent="Delete booking";button.onclick=()=>removeBooking(booking.calendar_event_id,button);article.appendChild(button)});
}
async function removeBooking(eventId,button){if(!confirm("Delete this booking from Google Calendar?"))return;button.disabled=true;button.textContent="Deleting…";try{const response=await fetch(`/api/delete-booking?id=${encodeURIComponent(eventId)}`,{method:"DELETE",headers:{Authorization:`Bearer ${session.access_token}`}}),data=await response.json();if(!response.ok)throw new Error(data.error||"Could not delete booking");await api(`/rest/v1/commission_jobs?calendar_event_id=eq.${encodeURIComponent(eventId)}`,{method:"DELETE",headers:{Prefer:"return=minimal"}});await refreshWeek()}catch(error){button.disabled=false;button.textContent="Delete booking";$("#syncMessage").textContent=error.message}}
function renderJobs(jobs){
 const breeTotal=jobs.filter(job=>job.worker==="Bree").reduce((sum,job)=>sum+Number(job.commission_amount||0),0),joanTotal=jobs.filter(job=>job.worker==="Joan").reduce((sum,job)=>sum+Number(job.commission_amount||0),0),weekSaved=jobs.length&&jobs.every(job=>job.week_saved_at);
 $("#summaryGrid").innerHTML=["Bree","Joan"].map(worker=>{const rows=jobs.filter(job=>job.worker===worker),final=rows.reduce((sum,job)=>sum+Number(job.final_amount||0),0),commission=rows.reduce((sum,job)=>sum+Number(job.commission_amount||0),0),unpaid=rows.filter(job=>!job.is_paid).reduce((sum,job)=>sum+Number(job.commission_amount||0),0);return `<article><span>${worker}</span><strong>${money(commission)}</strong><small>40% commission · ${rows.length} job${rows.length===1?"":"s"}</small><div><b>${money(final)}</b> collected · <b>${money(unpaid)}</b> unpaid</div></article>`}).join("");
 $("#jobCount").textContent=`${jobs.length} job${jobs.length===1?"":"s"}`;
 $("#jobsTable").innerHTML=jobs.length?`<div class="table detailed"><div class="table-head"><span>Customer details</span><span>Worker</span><span>Final amount</span><span>40% commission</span><span>Status</span></div>${jobs.map(job=>`<div class="table-row"><span class="customer-details"><input data-name="${job.id}" value="${escapeHtml(job.customer_name)}" aria-label="Customer name"><small>${escapeHtml(job.service)} · ${new Date(job.completed_at).toLocaleString("en-KE",{weekday:"short",day:"numeric",month:"short",hour:"numeric",minute:"2-digit",timeZone:"Africa/Nairobi"})}</small>${job.customer_phone?`<a href="tel:${escapeHtml(job.customer_phone)}">${escapeHtml(job.customer_phone)}</a>`:""}${job.customer_email?`<a href="mailto:${escapeHtml(job.customer_email)}">${escapeHtml(job.customer_email)}</a>`:""}${job.booking_notes?`<small class="saved-booking-notes">${escapeHtml(job.booking_notes)}</small>`:""}</span><span><select data-worker="${job.id}" aria-label="Worker"><option ${job.worker==="Unassigned"?"selected":""}>Unassigned</option><option ${job.worker==="Bree"?"selected":""}>Bree</option><option ${job.worker==="Joan"?"selected":""}>Joan</option></select></span><span><label class="amount"><small>KSh</small><input data-amount="${job.id}" type="number" min="0" step="1" value="${job.final_amount??""}" placeholder="0"></label></span><span>${money(job.commission_amount)}</span><span><label class="paid"><input data-paid="${job.id}" type="checkbox" ${job.is_paid?"checked":""}><i></i>${job.is_paid?"Paid":"Unpaid"}</label></span></div>`).join("")}</div>`:'<div class="empty"><strong>No completed jobs yet for this week.</strong><span>Bookings appear here automatically after their calendar end time.</span></div>';
 if(jobs.length)$("#jobsTable").insertAdjacentHTML("beforeend",`<div class="bottom-commission"><article><span>Bree receives</span><strong>${money(breeTotal)}</strong></article><article><span>Joan receives</span><strong>${money(joanTotal)}</strong></article><button id="saveWeek">Save this week’s work</button><p id="saveWeekMessage">${weekSaved?"This week’s work has been saved.":""}</p></div>`);
 document.querySelectorAll("[data-name]").forEach(input=>input.onchange=()=>updateJob(input.dataset.name,{customer_name:input.value.trim()||"Customer"}));
 document.querySelectorAll("[data-worker]").forEach(select=>select.onchange=()=>updateJob(select.dataset.worker,{worker:select.value}));
 document.querySelectorAll("[data-amount]").forEach(input=>input.onchange=()=>updateJob(input.dataset.amount,{final_amount:input.value===""?null:Number(input.value)}));
 document.querySelectorAll("[data-paid]").forEach(input=>input.onchange=()=>updateJob(input.dataset.paid,{is_paid:input.checked}));
 if($("#saveWeek"))$("#saveWeek").onclick=saveWeek;
}
async function saveWeek(){const button=$("#saveWeek");button.disabled=true;$("#saveWeekMessage").textContent="Saving this week…";try{await api(`/rest/v1/commission_jobs?week_start=eq.${isoDate(weekStart)}`,{method:"PATCH",headers:{"Content-Type":"application/json","Prefer":"return=minimal"},body:JSON.stringify({week_saved_at:new Date().toISOString()})});$("#saveWeekMessage").textContent="This week’s work has been saved.";await loadHistory()}catch(error){$("#saveWeekMessage").textContent=error.message}finally{button.disabled=false}}
async function updateJob(id,changes){try{await api(`/rest/v1/commission_jobs?id=eq.${id}`,{method:"PATCH",headers:{"Content-Type":"application/json","Prefer":"return=minimal"},body:JSON.stringify(changes)});await loadSavedWeek()}catch(error){$("#syncMessage").textContent=error.message}}
async function loadHistory(){const rows=await api("/rest/v1/commission_jobs?select=week_start,commission_amount,is_paid&order=week_start.desc"),weeks=[...new Set(rows.map(row=>row.week_start))].slice(0,12);$("#historyList").innerHTML=weeks.map(week=>{const items=rows.filter(row=>row.week_start===week),total=items.reduce((sum,row)=>sum+Number(row.commission_amount||0),0),paid=items.length&&items.every(row=>row.is_paid);return `<button data-week="${week}"><span>Week of ${new Date(`${week}T12:00:00+03:00`).toLocaleDateString("en-KE",{day:"numeric",month:"short",year:"numeric"})}</span><strong>${money(total)} · ${paid?"Paid":"Payment pending"}</strong></button>`}).join("")||"<p>No earlier records yet.</p>";document.querySelectorAll("[data-week]").forEach(button=>button.onclick=()=>{weekStart=new Date(`${button.dataset.week}T12:00:00+03:00`);refreshWeek()})}
async function loadSavedWeek(){renderWeekLabel();renderJobs(await getJobs());await loadHistory()}
const walkinDate=$("#walkinForm [name=completed_at]");
const setWalkinNow=()=>{walkinDate.value=new Intl.DateTimeFormat("sv-SE",{timeZone:"Africa/Nairobi",year:"numeric",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit"}).format(new Date()).replace(" ","T")};
setWalkinNow();
$("#walkinForm").onsubmit=async event=>{event.preventDefault();const form=event.currentTarget,button=form.querySelector('button[type="submit"]'),values=Object.fromEntries(new FormData(form)),completed=new Date(`${values.completed_at}:00+03:00`),start=mondayFor(completed),end=new Date(start);end.setDate(end.getDate()+5);button.disabled=true;$("#walkinMessage").textContent="Saving walk-in…";try{await api("/rest/v1/commission_jobs",{method:"POST",headers:{"Content-Type":"application/json","Prefer":"return=minimal"},body:JSON.stringify({calendar_event_id:`manual-${crypto.randomUUID()}`,worker:values.worker,customer_name:values.customer_name.trim(),customer_phone:values.customer_phone.trim(),service:values.service.trim(),booking_notes:values.booking_notes.trim(),completed_at:completed.toISOString(),week_start:isoDate(start),week_end:isoDate(end),final_amount:Number(values.final_amount)})});weekStart=start;form.reset();setWalkinNow();$("#walkinMessage").textContent="Walk-in saved. The 40% commission has been calculated.";await loadSavedWeek()}catch(error){$("#walkinMessage").textContent=error.message}finally{button.disabled=false}};
const availabilityForm=$("#attendantAvailabilityForm");
const allDay=availabilityForm.querySelector('[name="all_day"]');
allDay.onchange=()=>{
 for(const name of ["start","end"]){const input=availabilityForm.querySelector(`[name="${name}"]`),date=input.value.slice(0,10);input.type=allDay.checked?"date":"datetime-local";input.value=date?(allDay.checked?date:`${date}T${name==="start"?"08:00":"21:00"}`):""}
};
availabilityForm.onsubmit=async event=>{
 event.preventDefault();const values=Object.fromEntries(new FormData(availabilityForm)),button=availabilityForm.querySelector('button[type="submit"]');
 let start,end;
 if(allDay.checked){start=new Date(`${values.start}T00:00:00+03:00`);end=new Date(`${values.end}T00:00:00+03:00`);end.setUTCDate(end.getUTCDate()+1)}else{start=new Date(`${values.start}:00+03:00`);end=new Date(`${values.end}:00+03:00`)}
 if(!Number.isFinite(+start)||!Number.isFinite(+end)||end<=start){$("#availabilityMessage").textContent="Choose a valid start and end time.";return}
 button.disabled=true;$("#availabilityMessage").textContent="Saving unavailable period…";
 try{await changeAvailability('POST',{employee:values.employee,start:start.toISOString(),end:end.toISOString(),reason:values.reason});availabilityForm.reset();allDay.onchange();$("#availabilityMessage").textContent="Attendant marked unavailable. Clients cannot book this period.";await refreshWeek()}catch(error){$("#availabilityMessage").textContent=error.message}finally{button.disabled=false}
};
async function changeAvailability(method,body){
 const response=await fetch('/api/attendant-availability',{method,headers:{Authorization:`Bearer ${session.access_token}`,"Content-Type":"application/json"},body:JSON.stringify(body)}),data=await response.json();if(!response.ok)throw new Error(data.error||"Could not update availability");return data;
}
function renderUnavailable(periods){
 const format=value=>new Date(value).toLocaleString("en-KE",{day:"numeric",month:"short",hour:"numeric",minute:"2-digit",timeZone:"Africa/Nairobi"});
 $("#unavailablePeriods").innerHTML=periods.length?periods.map((period,index)=>`<article class="unavailable-period"><div><strong>${escapeHtml(period.employee)}</strong><p>${format(period.start)} – ${format(period.end)}</p>${period.reason&&period.reason!=="Not provided"?`<small>${escapeHtml(period.reason)}</small>`:""}</div><button type="button" data-restore-availability="${index}">Make available</button></article>`).join(""):'<p class="no-booking">No unavailable periods this week.</p>';
 document.querySelectorAll('[data-restore-availability]').forEach(button=>button.onclick=async()=>{const period=periods[Number(button.dataset.restoreAvailability)];button.disabled=true;try{await changeAvailability('DELETE',period);$("#availabilityMessage").textContent="Unavailable period removed.";await refreshWeek()}catch(error){$("#availabilityMessage").textContent=error.message;button.disabled=false}});
}
async function refreshWeek(){const button=$("#importCalendar");button.disabled=true;$("#syncMessage").textContent="Loading this week’s calendar…";try{const start=isoDate(weekStart),end=isoDate(weekEnd()),response=await fetch(`/api/admin-calendar?start=${start}&end=${end}`,{headers:{Authorization:`Bearer ${session.access_token}`}}),data=await response.json();if(!response.ok)throw new Error(data.error||"Calendar unavailable");renderCalendar(data.calendar||[]);renderUnavailable(data.unavailable||[]);if(data.jobs.length)await api("/rest/v1/commission_jobs?on_conflict=calendar_event_id",{method:"POST",headers:{"Content-Type":"application/json","Prefer":"resolution=ignore-duplicates,return=minimal"},body:JSON.stringify(data.jobs)});$("#syncMessage").textContent=`${data.calendar.length} booking${data.calendar.length===1?"":"s"} found · ${data.jobs.length} completed.`;await loadSavedWeek()}catch(error){$("#syncMessage").textContent=error.message;await loadSavedWeek()}finally{button.disabled=false}}
$("#importCalendar").onclick=refreshWeek;
$("#previousWeek").onclick=()=>{weekStart.setDate(weekStart.getDate()-7);refreshWeek()};
$("#nextWeek").onclick=()=>{weekStart.setDate(weekStart.getDate()+7);refreshWeek()};
let customerPage=0,customerSearch="",customerListRequest=0,customerDetailRequest=0;
async function customerRequest(query){const response=await fetch(`/api/admin-customers?${new URLSearchParams(query)}`,{headers:{Authorization:`Bearer ${session.access_token}`}}),data=await response.json();if(!response.ok)throw new Error(data.error||"Could not load customers");return data}
function renderCustomerList(customers){
 $("#customerList").innerHTML=customers.length?customers.map(customer=>`<button type="button" class="customer-account-choice" data-customer-id="${escapeHtml(customer.user_id)}"><strong>${escapeHtml(customer.full_name||customer.email||"Customer")}</strong><small>${escapeHtml(customer.email)}</small>${customer.phone?`<small>${escapeHtml(customer.phone)}</small>`:""}</button>`).join(""):'<p>No matching customer accounts.</p>';
 document.querySelectorAll('[data-customer-id]').forEach(button=>button.onclick=()=>loadCustomerAccount(button.dataset.customerId));
}
async function loadCustomers(){
 if(!session)return;const request=++customerListRequest;customerDetailRequest++;$("#customersMessage").textContent="Loading customer accounts…";$("#customerAccountDetail").innerHTML='<p>Select a customer to view their account.</p>';
 try{const data=await customerRequest({search:customerSearch,page:customerPage});if(request!==customerListRequest||!session)return;renderCustomerList(data.customers);$("#previousCustomers").disabled=customerPage===0;$("#nextCustomers").disabled=!data.hasMore;$("#customersMessage").textContent=`${data.customers.length} customer account${data.customers.length===1?"":"s"} on this page.`}catch(error){if(request!==customerListRequest||!session)return;$("#customersMessage").textContent=error.message;$("#customerList").innerHTML="";$("#previousCustomers").disabled=true;$("#nextCustomers").disabled=true}
}
function renderCustomerAccount(data){
 const customer=data.customer,historyAvailable=Array.isArray(data.appointments),appointments=data.appointments||[],completed=appointments.filter(item=>item.completed),upcoming=appointments.filter(item=>!item.completed).sort((a,b)=>new Date(a.starts_at)-new Date(b.starts_at));
 const date=value=>new Date(value).toLocaleString("en-KE",{day:"numeric",month:"short",year:"numeric",hour:"numeric",minute:"2-digit",timeZone:"Africa/Nairobi"});
 const rows=items=>items.length?items.map(item=>`<article class="customer-appointment"><strong>${escapeHtml(item.service)}</strong><p>${date(item.starts_at)}${item.stylist?` · ${escapeHtml(item.stylist)}`:""}</p><p><b>Drink:</b> ${escapeHtml(item.beverage&&item.beverage!=="Not selected"?item.beverage:"Not recorded")}</p>${item.booking_notes?`<details><summary>Booking details</summary><p class="saved-booking-notes">${escapeHtml(item.booking_notes)}</p></details>`:""}</article>`).join(""):'<p>No appointments in this period.</p>';
 const nextRetie=completed.length?new Date(new Date(completed[0].ends_at).getTime()+(customer.reminder_weeks||6)*7*86400000):null;
 $("#customerAccountDetail").innerHTML=`<h3>${escapeHtml(customer.full_name||customer.email||"Customer account")}</h3><dl class="customer-profile-fields"><dt>Email</dt><dd>${escapeHtml(customer.email||"Not provided")}</dd><dt>Phone</dt><dd>${escapeHtml(customer.phone||"Not provided")}</dd><dt>Birthday</dt><dd>${customer.birthday?new Date(`${customer.birthday}T12:00:00+03:00`).toLocaleDateString("en-KE",{day:"numeric",month:"long",year:"numeric",timeZone:"Africa/Nairobi"}):"Not provided"}</dd><dt>Retie reminder</dt><dd>${Number(customer.reminder_weeks)||6} weeks</dd><dt>Loyalty points</dt><dd>${historyAvailable?Number(data.points)||0:"Unavailable"}</dd><dt>Next suggested retie</dt><dd>${!historyAvailable?"Unavailable":nextRetie?date(nextRetie):"After first completed appointment"}</dd></dl><p class="customer-history-period">Showing the same history period as the customer account: past 2 years and next year.</p>${historyAvailable?`<h4>Upcoming bookings</h4>${rows(upcoming)}<h4>Completed appointments</h4>${rows(completed)}`:`<p class="message">${escapeHtml(data.historyError||"Booking history is unavailable.")}</p>`}`;
}
async function loadCustomerAccount(id){
 if(!session)return;const request=++customerDetailRequest;$("#customerAccountDetail").innerHTML='<p>Loading account…</p>';
 try{const data=await customerRequest({id});if(request!==customerDetailRequest||!session)return;renderCustomerAccount(data)}catch(error){if(request===customerDetailRequest&&session)$("#customerAccountDetail").innerHTML=`<p class="message">${escapeHtml(error.message)}</p>`}
}
$("#refreshCustomers").onclick=()=>{customerPage=0;loadCustomers()};
$("#customerSearchForm").onsubmit=event=>{event.preventDefault();customerSearch=String(new FormData(event.currentTarget).get("search")||"").trim();customerPage=0;loadCustomers()};
$("#previousCustomers").onclick=()=>{if(customerPage>0){customerPage--;loadCustomers()}};
$("#nextCustomers").onclick=()=>{customerPage++;loadCustomers()};
session?.access_token?showDashboard():showLogin();
